### PR TITLE
Fix two minor clippy lints

### PR DESCRIPTION
**Pull request by cgwalters**
I was looking at this project; this is also acting as an effective "is this project maintained?" ping.

### CODE REVIEW

**Comment by cgwalters** [comment]
Ping?

**Comment by cgwalters** [comment]
Ping @lucab - are you still maintaining this project?

**Comment by lucab** [comment]
Yes and no, I didn't get the initial notification from this PR. Anyway LGTM. Want to move this to `coreos/` too?

**Review by lucab — APPROVED** [review]

**Comment by cgwalters** [comment]
> Yes and no, I didn't get the initial notification from this PR. 

No worries!

> Want to move this to coreos/ too?

I'd like to use this in more projects (at the moment, looking at using it in https://github.com/containers/bootc) and it'd be good to know there's shared maintenance.

Moving to coreos/ seems fine from that perspective, but there's other paths like adding more maintainers here.  It seems simplest from a mechanics perspective in coreos/ but obviously your opinion weights highly here - what do you think?

Also, hope things are going well with you!

**Comment by lucab** [comment]
All good, thanks! I've added @cgwalters and @bgilbert as owners/admins for both the repository and the crate. Feel free to proceed with the move (and any other ACL tweaks).

**Comment by cgwalters** [comment]
OK filed https://github.com/coreos/fedora-coreos-tracker/issues/1395 to gather consensus

**Comment by bgilbert** [comment]
Moved to coreos/liboverdrop-rs.

**Pull request merged**
