### PR TITLE
Release 0.0.1

### PR DESCRIPTION
**Pull request by lucab**
liboverdrop 0.0.1:
 * initial release

### CODE REVIEW

**Review by rfairley — APPROVED** [review]
LGTM

**Comment by lucab** [comment]
Tagged: https://github.com/overdrop/liboverdrop-rs/releases/tag/0.0.1
Published: https://crates.io/crates/liboverdrop/0.0.1

**Comment by lucab** [comment]
@rfairley this one is ready for a round of fedora packaging too.

**Comment by rfairley** [comment]
Thanks! Just opened a Fedora package review request: https://bugzilla.redhat.com/show_bug.cgi?id=1720724

**Comment by rfairley** [comment]
`rust-liboverdrop` was accepted in Fedora and a Koji build has been completed for `rust-liboverdrop-0.0.1`! https://koji.fedoraproject.org/koji/taskinfo?taskID=35660922

**Pull request merged**
